_commit: v1.8.2-15-gf49812b
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: mqtt.crt.house
ingName: mosquitto
ingPathType: Prefix
ingWebSockets: false
ingress: true
labels: ''
name: mosquitto
namespace: mosquitto
pvc: false
reloader: true
resources:
- configmaps.yaml
- deployments.yaml
- ingresses.yaml
- services.yaml
service: false
serviceAccount: false
svcName: mosquitto
svcPortNum: 1883
upstreamURL: https://mosquitto.org
url: https://github.com/charlesthomas/homelab-mosquitto
