_commit: v1.9.0-1-g02b6330
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: ''
name: mosquitto
namespace: mosquitto
pvc: false
reloader: false
resources:
- configmaps.yaml
- deployments.yaml
- services.yaml
service: false
serviceAccount: false
upstreamURL: https://mosquitto.org
url: https://github.com/charlesthomas/homelab-mosquitto
