_commit: v1.8.2-15-gf49812b
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: ''
name: mosquitto
namespace: mosquitto
pvc: false
reloader: true
resources:
- configmaps.yaml
- deployments.yaml
- services.yaml
service: false
serviceAccount: false
upstreamURL: https://mosquitto.org
url: https://github.com/charlesthomas/homelab-mosquitto
