_commit: v1.8.1
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: mosquitto
helmRelease: mosquitto
helmRepo: https://charts.truecharts.org/
helmValues: helm/values.yaml
helmVersion: 11.0.17
homepageEnabled: true
ingHost: mosquitto.crt.house
ingName: mosquitto
ingress: false
labels: ''
name: mosquitto
namespace: mosquitto
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://mosquitto.org
url: https://github.com/charlesthomas/homelab-mosquitto
