---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mosquitto

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-mosquitto

resources:
- resources/configmaps.yaml
- resources/deployments.yaml
- resources/namespaces.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: mosquitto
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
