---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mosquitto

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-mosquitto

resources:
- resources/namespaces.yaml
helmCharts:
- name: mosquitto
  namespace: mosquitto
  releaseName: mosquitto
  repo: https://charts.truecharts.org/
  valuesFile: helm/values.yaml
  version: 11.0.17
