---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mosquitto

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-mosquitto

resources:
- resources/configmaps.yaml
- resources/deployments.yaml
- resources/namespaces.yaml
- resources/services.yaml
