---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
  annotations:
    repo: https://github.com/charlesthomas/homelab-mosquitto
  labels:
    app: mosquitto-11.0.17
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 2.0.18
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
