---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: mosquitto
    protocol: TCP
    name: mosquitto
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
    pod.name: main
