apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  annotations:
    repo: https://github.com/charlesthomas/homelab-mosquitto
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 2.0.18
    service.name: main
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: main
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
    pod.name: main
  sessionAffinity: None
  type: ClusterIP
